site_name: FOREST Lite
repo_url: https://github.com/MetOffice/forest-lite
nav:
  - Getting started: index.md
  - Developer guide: dev-guide.md
  - design.md
theme:
  name: material
  palette:
    scheme: default
    primary: light blue
    accent: blue
  favicon: img/favicon.png
  logo: img/logo_transparent_notext_white.png
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
