site_name: FOREST Lite
repo_url: https://github.com/MetOffice/forest-lite
nav:
  - FOREST Lite: index.md
  - beginner.md
  - design.md
theme:
  name: material
  palette:
    scheme: default
    primary: cyan
    accent: blue
  favicon: img/favicon.png
  logo: img/logo_transparent_notext_white.png
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
