// Action keywords
export const SET_ACTIVE = 'SET_ACTIVE'
export const SET_VISIBLE = 'SET_VISIBLE'
export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE'
export const SET_ONLY_ACTIVE = 'SET_ONLY_ACTIVE'
export const SET_URL = 'SET_URL'
export const SET_FIGURE = 'SET_FIGURE'
export const SET_DATASET = 'SET_DATASET'
export const SET_DATASETS = 'SET_DATASETS'
export const SET_DATASET_DESCRIPTION = "SET_DATASET_DESCRIPTION"
export const SET_DATASET_COLORBAR = "SET_DATASET_COLORBAR"
export const SET_PALETTE = 'SET_PALETTE'
export const SET_PALETTES = 'SET_PALETTES'
export const SET_PALETTE_NAME = 'SET_PALETTE_NAME'
export const SET_PALETTE_NAMES = 'SET_PALETTE_NAMES'
export const SET_PALETTE_NUMBER = 'SET_PALETTE_NUMBER'
export const SET_PALETTE_NUMBERS = 'SET_PALETTE_NUMBERS'
export const SET_PLAYING = 'SET_PLAYING'
export const SET_LIMITS = 'SET_LIMITS'
export const SET_STATE = 'SET_STATE'
export const SET_TIMES = 'SET_TIMES'
export const SET_TIME_INDEX = 'SET_TIME_INDEX'
export const NEXT_TIME_INDEX = 'NEXT_TIME_INDEX'
export const PREVIOUS_TIME_INDEX = 'PREVIOUS_TIME_INDEX'
export const FETCH_IMAGE = 'FETCH_IMAGE'
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS'
export const SET_FLAG = "SET_FLAG"
export const TOGGLE_FLAG = "TOGGLE_FLAG"
export const ZOOM_IN = "ZOOM_IN"
export const ZOOM_OUT = "ZOOM_OUT"

// Elm-only action types
export const SET_COASTLINES_COLOR = 'SET_COASTLINES_COLOR'
export const SET_COASTLINES_WIDTH = 'SET_COASTLINES_WIDTH'
export const GET_HTTP_NATURAL_EARTH_FEATURE = 'GET_HTTP_NATURAL_EARTH_FEATURE'
export const SET_HTTP_NATURAL_EARTH_FEATURE = 'SET_HTTP_NATURAL_EARTH_FEATURE'
export const SET_QUADKEYS = 'SET_QUADKEYS'

// WebWorker middleware
export const UPDATE_NATURAL_EARTH_FEATURE = 'UPDATE_NATURAL_EARTH_FEATURE'

// IndexedDB action types
export const GET_INDEXEDDB_NATURAL_EARTH_FEATURE = 'GET_INDEXEDDB_NATURAL_EARTH_FEATURE'
export const GOT_INDEXEDDB_NATURAL_EARTH_FEATURE = 'GOT_INDEXEDDB_NATURAL_EARTH_FEATURE'

// Navigation action types
export const UPDATE_NAVIGATE = "UPDATE_NAVIGATE"
export const GOTO_ITEM = 'GOTO_ITEM'
export const NEXT_ITEM = 'NEXT_ITEM'
export const PREVIOUS_ITEM = 'PREVIOUS_ITEM'
export const SET_ITEMS = 'SET_ITEMS'


// Elm interop
export const SET_PORTS = "SET_PORTS"
