-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ColorScheme exposing (..)

import Api.Enum.Kind
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


name : SelectionSet (Maybe String) Api.Object.ColorScheme
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


kind : SelectionSet (Maybe Api.Enum.Kind.Kind) Api.Object.ColorScheme
kind =
    Object.selectionForField "(Maybe Enum.Kind.Kind)" "kind" [] (Api.Enum.Kind.decoder |> Decode.nullable)


type alias PalettesOptionalArguments =
    { rank : OptionalArgument Int }


palettes :
    (PalettesOptionalArguments -> PalettesOptionalArguments)
    -> SelectionSet decodesTo Api.Object.Palette
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.ColorScheme
palettes fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { rank = Absent }

        optionalArgs____ =
            [ Argument.optional "rank" filledInOptionals____.rank Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "palettes" optionalArgs____ object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
