-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Palette exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


rank : SelectionSet (Maybe Int) Api.Object.Palette
rank =
    Object.selectionForField "(Maybe Int)" "rank" [] (Decode.int |> Decode.nullable)


rgbs : SelectionSet (Maybe (List (Maybe String))) Api.Object.Palette
rgbs =
    Object.selectionForField "(Maybe (List (Maybe String)))" "rgbs" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)
