-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Query exposing (..)

import Api.Enum.Kind
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias ColorSchemesOptionalArguments =
    { kind : OptionalArgument Api.Enum.Kind.Kind
    , rank : OptionalArgument Int
    , name : OptionalArgument String
    }


colorSchemes :
    (ColorSchemesOptionalArguments -> ColorSchemesOptionalArguments)
    -> SelectionSet decodesTo Api.Object.ColorScheme
    -> SelectionSet (Maybe (List (Maybe decodesTo))) RootQuery
colorSchemes fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { kind = Absent, rank = Absent, name = Absent }

        optionalArgs____ =
            [ Argument.optional "kind" filledInOptionals____.kind (Encode.enum Api.Enum.Kind.toString), Argument.optional "rank" filledInOptionals____.rank Encode.int, Argument.optional "name" filledInOptionals____.name Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "colorSchemes" optionalArgs____ object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
