name: docs
on:
  - push
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      python-version: 3.8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{env.python-version}}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
      - name: print version
        run: mkdocs --version
