name: docs
on:
  - push
    #  push:
    #    branches: main
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      python-version: 3.8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{env.python-version}}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: set up git
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
          git remote rm origin
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: mkdocs gh-deploy
        run: mkdocs gh-deploy
