name: github-actions
on: [push]
jobs:
  test-client:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      node-version: 14.x
      working-directory: forest_lite/client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.node-version}}
      - name: npm install
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: npm run build
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: npm test
        run: npm test
        working-directory: ${{env.working-directory}}
